    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Home - <?php echo $this->layout()->__get('title');?></title>
      <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
    </body>
    </html>