<?php echo $this->doctype(); ?>

<html>
    <head>
         <?php echo $this->headTitle('Blog Admin')->setAutoEscape(false) ?>

         <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

         <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/layout.css')?>
		 
    </head>
    <body>
       
        <header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">Site Admin</a></h1>
			<h2 class="section_title"></h2><div class="btn_view_site"><a href="#">Main Site</a></div>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<?php echo $this->content; ?>
	
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/hideshow.js')
                                       ->prependFile($this->basePath() . '/js/admin/jquery.equalHeight.js') 
         							   ->prependFile($this->basePath() . '/js/admin/jquery.tablesorter.min.js') 
         							   ->prependFile($this->basePath() . '/js/admin/main.js')
         							   ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>
    </body>
</html>    