<?php echo $this->doctype(); ?>
<html>
    <head>
         <?php echo $this->headTitle('Blog Admin')->setAutoEscape(false) ?>

         <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

         <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/layout.css')?>
		 
    </head>
    <body>
       
        <header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">Site Admin</a></h1>
                        <?php if(isset($this->logged)):?>
			<h2 class="section_title"></h2><div class="btn_view_site"><a href="/admin/logout">Logout</a></div>
                        <?php endif;?>
                </hgroup>
	</header> <!-- end of header bar -->
	<?php if(isset($this->logged)):?>
	<section id="secondary_bar">
		<div class="user">
			<p><?php echo ucfirst($this->username)?> </p>
		</div>
		<div class="breadcrumbs_container">
			<article class="breadcrumbs">
				<a href="index.html">Website Admin</a>
				<div class="breadcrumb_divider"></div>
				<a class="current"><?php if(isset($this->module_name)) echo $this->module_name; ?></a>
			</article>
		</div>
	</section>
	<?php endif?>
	
	<?php if(isset($this->logged)):?>
	<aside id="sidebar" class="column">
		<form class="quick_search">
			<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
		</form>
		<hr/>
		<h3>Content</h3>
		<ul class="toggle">
			<li class="icn_new_article"><a href="#">New Article</a></li>
			<li class="icn_edit_article"><a href="#">Edit Articles</a></li>
			<li class="icn_categories"><a href="#">Categories</a></li>
			<li class="icn_tags"><a href="#">Tags</a></li>
		</ul>
		<h3>Users</h3>
		<ul class="toggle">
			<li class="icn_add_user"><a href="#">Add New User</a></li>
			<li class="icn_view_users"><a href="#">View Users</a></li>
			<li class="icn_profile"><a href="#">Your Profile</a></li>
		</ul>
		<h3>Media</h3>
		<ul class="toggle">
			<li class="icn_folder"><a href="#">File Manager</a></li>
			<li class="icn_photo"><a href="#">Gallery</a></li>
			<li class="icn_audio"><a href="#">Audio</a></li>
			<li class="icn_video"><a href="#">Video</a></li>
		</ul>
		<h3>Admin</h3>
		<ul class="toggle">
			<li class="icn_settings"><a href="#">Options</a></li>
			<li class="icn_security"><a href="#">Security</a></li>
			<li class="icn_jump_back"><a href="#">Logout</a></li>
		</ul>
		
		<footer>
			<hr />
			<p><strong>Copyright &copy; 2011 Website Admin</strong></p>
			<p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
		</footer>
	</aside><!-- end of sidebar -->
	<?php endif;?>
	
		
	
	<?php echo $this->content; ?>
	
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/hideshow.js')
                                       ->prependFile($this->basePath() . '/js/admin/jquery.equalHeight.js') 
         							   ->prependFile($this->basePath() . '/js/admin/jquery.tablesorter.min.js') 
         							   ->prependFile($this->basePath() . '/js/admin/main.js')
         							   ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>
    </body>
</html>    