<?php echo $this->doctype(); ?>
<html>
    <head>
         <?php echo $this->headTitle('Blog Admin')->setAutoEscape(false) ?>

         <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

         <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/layout.css')?>
		 
    </head>
    <body>
       
        <header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">Site Admin</a></h1>
                        <?php if(isset($this->logged)):?>
			<h2 class="section_title"></h2><div class="btn_view_site"><a href="/admin/logout">Logout</a></div>
                        <?php endif;?>
                </hgroup>
	</header> <!-- end of header bar -->
	<?php if(isset($this->logged)):?>
	<section id="secondary_bar">
		<div class="user">
			<p><?php echo ucfirst($this->username)?> </p>
		</div>
		<div class="breadcrumbs_container">
			<article class="breadcrumbs">
				<a href="index.html">Website Admin</a>
				<div class="breadcrumb_divider"></div>
				<a class="current"><?php if(isset($this->module_name)) echo $this->module_name; ?></a>
			</article>
		</div>
	</section>
	<?php endif?>
	
	<?php if(isset($this->logged)):?>
	
	<aside id="sidebar" class="column">
		<form class="quick_search">
			<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
		</form>
		<hr/>
		<?php foreach($this->user_modules as $module): ?>
			<h3><?php echo ucfirst($module->name)?></h3>
			<ul class="toggle">
				<?php foreach(json_decode($module->sections,true) as $section=>$class):?>
				<li class="<?php echo $class ?>"><a href="#"><?php echo ucfirst(str_replace("_"," ",$section))?></a></li>
				<?php  endforeach ?>
			</ul>
		<?php endforeach;?>
		<footer>
			<hr />
			<p><strong>Copyright &copy; 2011 Website Admin</strong></p>
			<p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
		</footer>
	</aside><!-- end of sidebar -->
	<?php endif;?>
	
		
	
	<?php echo $this->content; ?>
	
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/hideshow.js')
                                       ->prependFile($this->basePath() . '/js/admin/jquery.equalHeight.js') 
         							   ->prependFile($this->basePath() . '/js/admin/jquery.tablesorter.min.js') 
         							   ->prependFile($this->basePath() . '/js/admin/main.js')
         							   ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>
    </body>
</html>    